# Bag Of Words

** Step 1 : Tokenize the data, remove stop words and perform stemming or lemmatization**

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [ ]:
paragraph ="The news mentioned here is fake fake. Audience do not encorage fake news . Fake news is false or misleading "

sentences =nltk.sent_tokenize(paragraph)
print(sentences)
lemmatizer =WordNetLemmatizer()
print(lemmatizer)

corpus = []

for i in range(len(sentences)):
  sent = re.sub('[^a-zA-Z]',' ',sentences[i])
  print(sent)
  sent = sent.lower()
  sent = sent.split()
  stop_wrd = set(stopwords.words("english"))
  #print(stop_wrd)

  sent =[lemmatizer.lemmatize(word) for word in sent if not word in stop_wrd]
  print(sent)
  sent =''.join(sent)
  corpus.append(sent)
print(corpus)




['The news mentioned here is fake fake.', 'Audience do not encorage fake news .', 'Fake news is false or misleading']
<WordNetLemmatizer>
The news mentioned here is fake fake 
['news', 'mentioned', 'fake', 'fake']
Audience do not encorage fake news  
['audience', 'encorage', 'fake', 'news']
Fake news is false or misleading
['fake', 'news', 'false', 'misleading']
['newsmentionedfakefake', 'audienceencoragefakenews', 'fakenewsfalsemisleading']


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
independentFeatures = cv.fit_transform(corpus).toarray()
print(independentFeatures)

[[0 0 1]
 [1 0 0]
 [0 1 0]]


# Text Representation - Bag  of word

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive


In [ ]:
df=pd.read_csv('/content/gdrive/My Drive/ML_practical/Bag_of_word/spam_1.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
df.shape

(5572, 3)

In [ ]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

Create bag of words representation using CountVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
v = CountVectorizer()

In [ ]:
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7704 sparse matrix of type '<class 'numpy.int64'>'
	with 59294 stored elements in Compressed Sparse Row format>

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
v.vocabulary_

{'dude': 2479,
 'what': 7434,
 'up': 7146,
 'how': 3511,
 'teresa': 6732,
 'hope': 3479,
 'you': 7662,
 'have': 3351,
 'been': 1299,
 'okay': 4914,
 'when': 7440,
 'didnt': 2306,
 'hear': 3371,
 'from': 3013,
 'these': 6797,
 'people': 5137,
 'called': 1624,
 'them': 6786,
 'and': 969,
 'they': 6802,
 'had': 3288,
 'received': 5611,
 'the': 6777,
 'package': 5046,
 'since': 6155,
 'dec': 2206,
 'lt': 4242,
 'gt': 3253,
 'just': 3866,
 'thot': 6827,
 'ld': 4042,
 'like': 4107,
 'to': 6900,
 'know': 3955,
 'do': 2374,
 'fantastic': 2777,
 'year': 7636,
 'all': 919,
 'best': 1332,
 'with': 7505,
 'your': 7668,
 'reading': 5583,
 'plus': 5255,
 'if': 3591,
 'can': 1641,
 'really': 5593,
 'bam': 1221,
 'first': 2874,
 'aid': 887,
 'for': 2933,
 'usmle': 7191,
 'then': 6790,
 'work': 7551,
 'is': 3738,
 'done': 2406,
 'hey': 3411,
 've': 7225,
 'booked': 1435,
 'pilates': 5207,
 'yoga': 7658,
 'lesson': 4079,
 'already': 932,
 'haha': 3290,
 'idk': 3587,
 'sitting': 6174,
 'here': 3403,
 'in

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.naive_bayes import MultinomialNB


In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
y_pred = model.predict(X_test_cv)


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       957
           1       0.98      0.89      0.93       158

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

